pipeline{
    agent any

    tools{
        maven 'Maven 3.9'
    }

    stages{
        stage('Checkout Code'){
            steps{
                checkout scm
            }
        }

        stage('Build and Test'){
            steps{
                dir('demo-api'){
                    sh 'mvn clean install'
                }
            }
        }
    }
}